### ISSUE TITLE
Signature not faked

### ISSUE THREAD

**Issue by Tentos** [thermatk/FakeGApps#1]
Hello thermatk,

Thank you for your xposed module. :-) It seems it has given a lot of people the possibility to use the microg GMS Core service by mar-v-in.
I have followed the instructions on the NoGapps XDA thread, but the apps relying on GApps tell me that my device does not support GApps when microg GMS Core has been installed. However, they instead show me the dialog to install the Google Apps if GMS Core is not installed, so the installation of microg GMS Core seems to have an effect.

My impression is that the signature is not correctly faked on my smartphone. I have checked the signature displayed by Application Info for microg services, and it is identical when FakeGApps is activated and deactivated. Moreover, the signature does not correspond to the one I have found in the source code of FakeGApps.

The xposed log gives the following when FakeGApps is loaded:
```
/data/app/com.thermatk.android.xf.fakegapps-2.apk
  Loading class com.thermatk.android.xf.fakegapps.FakeSignatures
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
	at dalvik.system.DexFile.defineClass(Native Method)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
	at dalvik.system.DexPathList.findClass(DexPathList.java:313)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at de.robv.android.xposed.XposedBridge.loadModule(XposedBridge.java:421)
	at de.robv.android.xposed.XposedBridge.loadModules(XposedBridge.java:386)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:120)
	at dalvik.system.NativeStart.main(Native Method)
```
Could there be an error on my smartphone? I am running Android 4.2.2 (no Custom ROM available yet), and i can try to provide a logcat if you think that there is indeed a problem.

**Comment by bonanza123** [comment]
I'm having the same issues on my maguro running CM11 (4.4.4). On my CM12.1 hammerhead its working fine. My current guess is that its due to a different Xposed or CM version.

**Comment by bonanza123** [comment]
Please check out my fork and the provided APK there, thanks.

**Comment by Tentos** [comment]
Your fork works as expected. Excellent! :+1:

**Comment by thermatk** [comment]
@bonanza123 Maybe I will convert this repo to an organization and add you? 
It's always better to have a community around one project

**Comment by julienschmidt** [comment]
Or you could ask @mar-v-in if this could become part of the µg project :wink:

**Comment by bonanza123** [comment]
@thermatk thanks!
