### ISSUE TITLE
Signature spoofing does not work

### ISSUE THREAD

**Issue by GuzTech** [thermatk/FakeGApps#14]
Dear thermatk,

I've got a BV6000 phone running their latest stock Android 6.0 ROM (22/08/16) that I've rooted. All the Google apps are removed, Xposed with framework SDK23 is installed, and FakeGApps 1.1 is also installed.

After installing MicroG Services Core (0.2.4-22-gcb356d2), Services Framework (0.1.0), and FakeStore (0.0.1), I've rebooted and when I do a self-check I see that everything except signature related entries are unchecked.

I did the same thing with my Moto G running CyanogenMod (Android 4.4) and that one works just fine. Is this because of Android 6 vs 4.4, or is it the stock vs CyanogenMod ROMs? I've done this before, but are the steps different for Android 6?

(btw, I've asked this on the MicroG core apps repo as well, but since I don't know where the problem lies, I wanted to ask here as well).

**Comment by bonanza123** [comment]
I recall that you have to go the microg permissions configuration (in android system settings) and enable the spoofing permission.

**Comment by GuzTech** [comment]
@bonanza123 Unfortunately I don't have such an option anywhere in the system settings. There is an "App permissions" section, but the MicroG Services Core  app only has the Email, MMS, and position permissions.

I've also read the *#*#CHECKIN#*#* thing, but when I enter it, it just dissappears and nothing happens.

**Comment by bonanza123** [comment]
I know this setting is well hidden. Check the app specific settings (not the listing on a per permission basis )

**Comment by bonanza123** [comment]
When thinking again about it, it have been an omnirom specific setting that i mean. Sorry I'm not using android anymore (sailfish FTW ;-))

**Comment by GuzTech** [comment]
Yeah, I was just writing that I've looked at the app specific settings already before your last comment :P Hopefully it's something small that I (or thermatk) can fix :)

**Comment by bonanza123** [comment]
Please don't forget to provide the xposed logs.

**Comment by GuzTech** [comment]
@bonanza123 The log is actually empty.

**Comment by bonanza123** [comment]
If the log is completely empty, then xposed is maybe not loaded. What does the xposed install / update menu show ? does it recognize xposed framework ?

**Comment by GuzTech** [comment]
Under Framework it says that Xposed framework version 86 is active in green.

**Comment by bonanza123** [comment]
But then it also normally puts info into the xposed log upon boot for example or on module load. Please check that the module is enabled and check the log again after boot and post everything what's there .

**Comment by thermatk** [comment]
@GuzTech @bonanza123 activating the module and rebooting should be enough. There is no reason to tick something in settings, this was for the Omni versions with builtin spoofing I think. Are you sure you activated the module after installing?

**Comment by GuzTech** [comment]
I just rebooted just in case, but the log is still empty. FakeGapps has a tick next to it, so it should be active. Like I said in the OP, I did the same thing on my Moto G (CyanogenMod Android 4.4), and that one works flawlessly. This phone however does run a stock ROM so I'm guessing it has to do with that.

**Comment by bonanza123** [comment]
If there is still nothing in the log (not even the info that it loaded the module ) then it may be an xposed issue. some ROMs of some vendors need special xposed handling like Samsung for example .

**Comment by thermatk** [comment]
In this case it might make sense to try any other Xposed module?

**Comment by GuzTech** [comment]
I removed, rebooted, reinstalled, and rebooted my phone, and I still don't have anything in the log.

Btw, I'm running Xposed 3.0 alpha 4, and Framework version 86. According to the XDA thread, this is the only one that works with 6.0.

**Comment by GuzTech** [comment]
Could it have anything to do with that I apparently need a de-odexed ROM? Because with Needle, you can also spoof signatures, but it doesn't work because I need a de-odexed ROM.

Btw, I just removed Xposed Installer + Framework, reinstalled everything, and now the log says that it cannot open /data/data/...../log/error.log, and that file does not exist (as seen using adb shell).

**Comment by GuzTech** [comment]
@thermatk Oh sorry, now I understand what you meant. I've tried another module "Call Blacklist Pro" and it works just fine. With adb shell I created an empty error.log file and the log is now empty and stays empty (even after installing call blacklist pro).

**Comment by sorcer1122** [comment]
I am also having the same problem with EMUI (Huawei's Adnroid 6.0). Tried everything (different versions of Xposed, clearing Dalvik, reinstalling, rebooting) - nothing helps. 

Any advice, guys? I really want to get MicroG working.

**Comment by sorcer1122** [comment]
The issue is resolved, many thanks for the help!!

**Comment by GuzTech** [comment]
@sorcer1122 Would you mind explaining how you resolved it?

**Comment by bonanza123** [comment]
@GuzTech if I remember correctly you need to have an de-odexed ROM. Try e.g. http://forum.xda-developers.com/showthread.php?t=2726658
