### ISSUE TITLE
Spoofing not working with microG

### ISSUE THREAD

**Issue by bytemybits** [thermatk/FakeGApps#16]
I've updated my OPO to the latest CM14.1 and has to reinstall everything microG and FakeGApps related. My problem now is that microG isn't detecting Signature Spoofing and I've rebooted/installed/uninstalled FakeGApps a couple of times trying to make it work.
The version of FakeGApps I'm using is 1.1 (the latest).
Is this version compatible with Nougat (7.1)?

**Comment by thermatk** [comment]
AFAIK, there is no Xposed for Nougat yet

сб, 19 нояб. 2016 г., 15:33 José Martins <notifications@github.com>:
