### ISSUE TITLE
Google maps doesn't work with FakeGapps xposed module

### ISSUE THREAD

**Issue by vephinx** [thermatk/FakeGApps#17]
I do not have gapps installed. I install google maps from the blank store.

With Xposed installed and superSU installed on cyanogenmod 13, with no xposed modules active, Google maps works fine. When I enable the FakeGapps module, Google maps no longer works. Instead google maps crashes on open with "Unfortunately, Maps has stopped".

**Comment by bonanza123** [comment]
Please provide logs from xposed and the android system. Do you have microG installed? And if so, which version and where did you download it?
