### ISSUE TITLE
Signal and LibreSignal doesn`t work

### ISSUE THREAD

**Issue by Jumbok** [thermatk/FakeGApps#18]
Signal/LibreSignal doesn`t work with CyanogenMod 11 (4.4.4) with microG + BlankStore + FakeGApps installed.
It says i must update play-services before the app Start.

At OmniROM (4.4.4) with the same installs without FakeGApps (because it has nativ signature spoofing) it works without problems.

So i think that the issue cames from FakeGApps.

**Comment by bonanza123** [comment]
Did you try installing the latest microg version, e.g. from https://microg.org/download.html ?

**Comment by Jumbok** [comment]
Die you mean the preview release?

I have installed the current stable releases.

Sorry for my bad english.

**Comment by bonanza123** [comment]
Yes, try latest latest preview/development/nightly build e.g. from fdroid.

**Comment by Jumbok** [comment]
Now i have installed microG Services Core 0.2.4-39 and it works! :)

Thanks for your help and for this project.
