### ISSUE TITLE
Allows unlimited spoofing?

### ISSUE THREAD

**Issue by matthijskooijman** [thermatk/FakeGApps#19]
If I read [the code correctly](https://github.com/thermatk/FakeGApps/blob/master/app/src/main/java/com/thermatk/android/xf/fakegapps/FakeSignatures.java#L24-L34), this module allows any other app to spoof the com.google.android.gms and com.android.vending identifiers, without any further checks. Looking at the [patch recommended by microg/gmscore](https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-M.patch), they introduce a new permission that allows apps to spoof signature permissions.

Is this understanding correct? Would it not be better to adopt the same approach as that patch to limit which apps can use this spoofing?

**Comment by thermatk** [comment]
Hi! If you want it so much, make a PR and nobody will be against it, but as you might find it in a review of security of microg spoofing(Google it, it was written when CM rejected the patches), Android doesn't use these signature checks anywhere, except for checking play services and play store... And it's advised not to do it that way in the developer documentation. 
Finally, no app can gain this permission even if it's done like that, unless you don't read which permissions you give the apps when you install them
