### ISSUE TITLE
Please add README.md

### ISSUE THREAD

**Issue by IzzySoft** [thermatk/FakeGApps#2]
Could you please add at least a basic `README.md` to this project, explaining

* what this module does
* hints on installing/usage (if needed)

Without knowing what it's for, it's hard to tell whether that's what one needs. In my case, I need something making *UnifiedNlp* work on a device with stock ROM (or course having *GApps* pre-installed), where *XposedUnifiedNlp* obviously doesn't do that job. Would your module be of help here? Hard to tell without some basic info :innocent:

Btw: Will you upload your module to the Xposed repo?

**Comment by bonanza123** [comment]
I added a preliminary readme to my fork: https://github.com/bonanza123/FakeGApps

**Comment by IzzySoft** [comment]
Thanks a lot, @bonanza123 – I see you've even included it with your pull request, great! Finally something for starters to follow :thumbsup:

**Comment by thermatk** [comment]
Merged
It's great to see that my idea is used, didn't really expect it after the initial skepticism :)

**Comment by IzzySoft** [comment]
Thanks a lot, @thermatk – that just leaves the question with the Xposed repo open :stuck_out_tongue_winking_eye:

**Comment by bonanza123** [comment]
I'm actually not sure whether this is needed. I currently don't think that any further changes to this module are needed, which maybe makes the advantages of easy updating via Xposed Installer obsolete.

**Comment by julienschmidt** [comment]
It would also make it easier for people to discover this module (and µg).
And if there might be an update necessary in the future, it certainly doesn't hurt to have it in the repo :wink:

**Comment by IzzySoft** [comment]
I agree with @julienschmidt here. Not everyone will search Github for modules. First place for most people certainly is the repo (after Playstore, maybe). There then should be a link pointing here, especially for any possible issues.
