### ISSUE TITLE
Slack reports out-of-date signature

### ISSUE THREAD

**Issue by Beatzekatze** [thermatk/FakeGApps#20]
Hi (and thanks for FakeGapps 👍 )

All apps (WhatsApp, Telegram, ...) work fine, Slack is the only one complaining about outdated signature on Google Play-Services.  `logcat` gives me following:
```
7-02 12:06:31.982  2587  4304 I Xposed  : FakeGApps: returning fake signature to com.Slack
07-02 12:06:31.983 28065 28094 W GooglePlayServicesUtil: Google Play services out of date.  Requires 9452000 but found 9258259

[12:09] 07-02 12:06:31.984 28065 28065 W FA      : Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
```

The issue might be similar to https://github.com/thermatk/FakeGApps/issues/15 . Not sure though...?  Xposed selftest says signature spoofing works

**Comment by bonanza123** [comment]
Make sure you have the latest (beta) version of microG. Confirm with https://microg.org/ if needed.

**Comment by Beatzekatze** [comment]
Thanks, solved it!
