### ISSUE TITLE
No effect on MM (EMUI)

### ISSUE THREAD

**Issue by Ph1r3ph0x** [thermatk/FakeGApps#21]
Hey :) 

first of all thank you for the efford of making this Xposed Module!
I tried it with my rooted honor 7 running Huawei's EMUI 4.0.3 and I cannot get it to work. Before I go through the efford of deodexing and patching the framework.jar I'd rather get this to work :D 
The Xposed Log lookes like this:

`10-26 14:30:38.438 E/Xposed  ( 3557): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.os.IPackageNameService.getPackageName(int)' on a null object reference
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.os.PackageNameServiceManager.getPackageName(PackageNameServiceManager.java:33)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at com.thermatk.android.xf.fakegapps.FakeSignatures$1.afterHookedMethod(FakeSignatures.java:26)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.content.pm.PackageParser.generatePackageInfo(<Xposed>)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.generatePackageInfo(PackageManagerService.java:2859)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:2909)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:145)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at com.android.server.GraphicsStatsService.isValid(GraphicsStatsService.java:81)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at com.android.server.GraphicsStatsService.requestBufferForProcess(GraphicsStatsService.java:96)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.view.IGraphicsStats$Stub.onTransact(IGraphicsStats.java:55)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(Binder.java:453)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
10-26 14:30:38.438 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(<Xposed>)
10-26 14:30:39.597 E/Xposed  ( 3557): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.os.IPackageNameService.getPackageName(int)' on a null object reference
10-26 14:30:39.597 E/Xposed  ( 3557): 	at android.os.PackageNameServiceManager.getPackageName(PackageNameServiceManager.java:33)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at com.thermatk.android.xf.fakegapps.FakeSignatures$1.afterHookedMethod(FakeSignatures.java:26)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at android.content.pm.PackageParser.generatePackageInfo(<Xposed>)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.generatePackageInfo(PackageManagerService.java:2859)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:2909)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:82)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:2807)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:510)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(Binder.java:453)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
10-26 14:30:39.597 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(<Xposed>)
10-26 14:30:39.635 E/Xposed  ( 3557): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.os.IPackageNameService.getPackageName(int)' on a null object reference
10-26 14:30:39.635 E/Xposed  ( 3557): 	at android.os.PackageNameServiceManager.getPackageName(PackageNameServiceManager.java:33)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at com.thermatk.android.xf.fakegapps.FakeSignatures$1.afterHookedMethod(FakeSignatures.java:26)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at android.content.pm.PackageParser.generatePackageInfo(<Xposed>)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.generatePackageInfo(PackageManagerService.java:2859)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:2909)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:82)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:2807)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:510)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(Binder.java:453)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
10-26 14:30:39.635 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(<Xposed>)
10-26 14:30:39.661 E/Xposed  ( 3557): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.os.IPackageNameService.getPackageName(int)' on a null object reference
10-26 14:30:39.661 E/Xposed  ( 3557): 	at android.os.PackageNameServiceManager.getPackageName(PackageNameServiceManager.java:33)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at com.thermatk.android.xf.fakegapps.FakeSignatures$1.afterHookedMethod(FakeSignatures.java:26)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at android.content.pm.PackageParser.generatePackageInfo(<Xposed>)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.generatePackageInfo(PackageManagerService.java:2859)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:2909)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:82)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:2807)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:510)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(Binder.java:453)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:337)
10-26 14:30:39.661 E/Xposed  ( 3557): 	at android.os.Binder.execTransact(<Xposed>)
10-26 14:30:39.684 E/Xposed  ( 3557): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.os.IPackageNameService.getPackageName(int)' on a null object reference
10-26 14:30:39.684 E/Xposed  ( 3557): 	at android.os.PackageNameServiceManager.getPackageName(PackageNameServiceManager.java:33)
10-26 14:30:39.684 E/Xposed  ( 3557): 	at com.thermatk.android.xf.fakegapps.FakeSignatures`

Maybe you can make something out of this. I really have no clue what this means :S 

Greetz Ph1r3ph0x

**Comment by thermatk** [comment]
Hi!
Looks like Huawei implemented things differently from AOSP.
Yet, it's possible to fix pretty easily - by making [line 26](https://github.com/thermatk/FakeGApps/blob/master/app/src/main/java/com/thermatk/android/xf/fakegapps/FakeSignatures.java#L26) check for `null`. Luckily, this line is used only for logging purposes and wouldn't hurt functionality, if it wouldn't fail. May be I'll do it in the coming days 👍

**Comment by Ph1r3ph0x** [comment]
Oh wow, that'd be awesome! I would try myself but I don't know have the sdk set up and never worked with xposed before.

Thx :)

**Comment by thermatk** [comment]
@Ph1r3ph0x 
please try https://github.com/thermatk/FakeGApps/releases/tag/2.0

**Comment by Ph1r3ph0x** [comment]
It works!! Thank you so much!
