### ISSUE TITLE
OnePlus 5T OxygenOS 5.1.6 - Signature Spoofing Disabled

### ISSUE THREAD

**Issue by 0pLuS0** [thermatk/FakeGApps#35]
In OxygeOS 5.1.5 FakeGapps was working to apply Signature Spoofing, microG shows the support is checked, and the "Signature Spoofing Checker" app from F-Droid it shows in Green Enabled.

But in the latest release of 5.1.6 the "Signature Spoofing Checker" app shows Disabled...

How can I determine if FakeGapps is working correctly, applying Signature Spoofing?

I'm not sure if FakeGapps is no longer working, or if this is a bug in the Signature Spoofing Checker?

Hmm

**Comment by thermatk** [comment]
Checker is ignoring fakegapps and doesn't want this bug fixed, you're good

**Comment by 0pLuS0** [comment]
@thermatk why would it showed enabled in one Android version and Disabled in another? I'm trying to at least understand this?

Because if you are saying FakeGapps is the only issue, that hasn't changed, the only thing that has changed is a ROM version, so I'm trying to understand where that comes into play effecting all of this, if you could please explain?

Thanks

**Comment by 0pLuS0** [comment]
@thermatk why would it showed enabled in one Android version and Disabled in another? I'm trying to at least understand this?

Who doesn't want to fix a bug, you or Checker?

Because if you are saying FakeGapps is the only issue, that hasn't changed, the only thing that has changed is a ROM version, so I'm trying to understand where that comes into play effecting all of this, if you could please explain?


Thanks

**Comment by 0pLuS0** [comment]
@thermatk why would it showed enabled in one Android version and Disabled in another? I'm trying to at least understand this?

Who doesn't want to fix a bug, you or Checker?

How else can someone check that Signature Spoofing is working correctly besides the Checker and microG?

Because if you are saying FakeGapps is the only issue, that hasn't changed, the only thing that has changed is a ROM version, so I'm trying to understand where that comes into play effecting all of this, if you could please explain?


Thanks

**Comment by thermatk** [comment]
Trust microg, because checker checks for something else and is not related if your goal is to run microg

**Comment by 0pLuS0** [comment]
@thermatk ok thanks
