### ISSUE TITLE
can't update microG core from fdroid

### ISSUE THREAD

**Issue by geg2048** [thermatk/FakeGApps#8]
This should be possible, right?

And I am also getting:
I/Xposed  (  800): FakeGApps: not returning fake signature to org.fdroid.fdroid

So is should get the real signature, but fdroid keeps saying that it's not the same.

**Comment by bonanza123** [comment]
I guess it's a different issue. Is it possible that you are now trying to install a GmsCore apk which is signed with a different key than your current version? 

Btw, check out the xposed module xinstaller, that should help here.

**Comment by bonanza123** [comment]
The xinstaller option you are looking for is "confirming signature check".

**Comment by geg2048** [comment]
After some research I think I found the problem.
I do actually need the fake signature from FakeGApps because the <sig> tag on the https://microg.org/fdroid/repo/index.xml does use the fake signatue.

**Comment by bonanza123** [comment]
I'm still convinced that your problem is caused by different signatures of your installed gmscore apk and the one you would like to update with. please provide a logcat of the error

**Comment by thermatk** [comment]
@bonanza123 thank you for taking down the PR, could be a real problem at this point :)
@geg2048 are you using the special repository described on https://microg.org/fdroid/ ?

**Comment by geg2048** [comment]
Ok im going to explain it:

i checked my signature and the sha256 value of my installed app and the app of the fdroid repo they are both the same:
$ keytool -list -printcert -jarfile com.google.android.gms-8489277.apk

Owner: O=NOGAPPS Project, C=DE
Issuer: O=NOGAPPS Project,C=DE

Serial number: 26ffa009

Valid from: Sat Oct 06 14:05:32 CEST 2012 until: Wed Sep 30 14:05:32 CEST 2037
Certificate fingerprints:
MD5:  6C:B7:75:5E:B8:16:51:83:A0:7D:A7:AA:BE:E4:DC:55 
SHA1: 10:32:1B:D8:93:F6:9A:F9:7F:75:73:AA:FE:9D:E1:DC:09:01:F3:A1
SHA256:9B:D0:67:27:E6:27:96:C0:13:0E:B6:DA:B3:9B:73:15:74:51:58:2C:BD:13:8E:86:C4:68:AC:C3:95:D1:41:65

Signature algorithm name: SHA256withRSA
Version: 3

If you are going to download this file  https://microg.org/fdroid/repo/index.xml you see that this:

\<package\>
    \<version\>8.4.89 (microG v0.2.0)\</version\>
    \<versioncode\>8489277\</versioncode\>
    \<apkname\>com.google.android.gms-8489277.apk\</apkname\>
    \<hash type="sha256"\>119dbdfa66120a852492d0c017a46c848c1f4a34f3ae29be620aa2de161b3abc\</hash\>
    \<sig\>d91564be0d13dcff260fe019eeea8cd8\</sig\>
\</package\>

sig = d91564be0d13dcff260fe019eeea8cd8
this value is generated by this tool: https://github.com/f-droid/fdroidserver/tree/master/tests/getsig and used to check the apk signature which are:

microG GsmCore apk
$ java getsig com.google.android.gms-8489277.apk
Result:ca625df9dd76b6002de9c94d216cf09b

Original Google apk   
$ java getsig GoogleServicesFramework.apk                        Result:d91564be0d13dcff260fe019eeea8cd8

You see that the provided signature d91564be0d13dcff260fe019eeea8cd8 is which is not the signature of the microG GsmCore apk (ca625df9dd76b6002de9c94d216cf09b).
which is total logical because only FakeGApps whitelistes fdroid but the omnirom fakesignature patch does not.

I hope you understand me now I am sorry that I didnt give a proper explanation before.

**Comment by geg2048** [comment]
@thermatk yes the offical microg fdroid repo
https://github.com/microg/android_packages_apps_GmsCore/wiki/Downloads

**Comment by geg2048** [comment]
I also installed a version without the froid filtering and it worked

**Comment by geg2048** [comment]
OK I looked around and found this https://github.com/microg/android_packages_apps_GmsCore/issues/92 which is basically my problem

**Comment by thermatk** [comment]
MaR-V-iN says in the XDA thread he might provide a solution in the coming weeks, let's wait. Meanwhile, you can update manually, no?

**Comment by geg2048** [comment]
@thermatk sure no problem there and thanks for the help

**Comment by mar-v-in** [comment]
@thermatk As ROM patches are not very dynamic and we won't see a proper adaption in all patches soon, I'd propose to go the other way round and spoof signature to F-Droid as well. This should allow FakeGapps users to use the F-Droid repo until we find a better solution...

**Comment by thermatk** [comment]
@mar-v-in the only other option at the time would be xposed-hacking the F-Droid logic :)
@geg2048 will upload to XposedRepo soon
